name: nawah
description: "Nawah - Professional Healthcare Consultation Platform"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2
 
environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  gap: ^3.0.1
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.5
  pretty_dio_logger: ^1.4.0
  quickalert: ^1.1.0
  device_info_plus: ^11.3.0
  flutter_native_splash: ^2.4.4
  restart_app: ^1.3.2
  rxdart: ^0.28.0
  easy_localization: ^3.0.7+1
  shared_preferences: ^2.5.3
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  marquee_list: ^1.0.0
  marqueer: ^2.0.1
  image_picker: ^1.1.2
  dotted_border: ^3.1.0
  persistent_bottom_nav_bar_v2: ^6.1.0
  flutter_secure_storage: ^9.2.4
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.2
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.5

flutter:


  uses-material-design: true

  assets:
    - assets/langs/
    - assets/images/  
    - assets/images/main/
    - assets/images/welcome/
    - assets/images/icons/
    - assets/images/flags/

  fonts:
   
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500 
        - asset: assets/fonts/Urbanist/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ThinItalic.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
